### ISSUE TITLE
I am unable to compile autogrid with mingw64

### ISSUE THREAD

**Issue by kotenok2000** [ccsb-scripps/AutoGrid#8]
It fails with two errors:

```
main.cpp:2634:29: error: 'bzero' was not declared in this scope
 2634 |         double meanvect[3]; bzero(meanvect, sizeof meanvect);
      |                             ^~~~~
```
 and 
```
main.cpp: In function 'int main(int, char**)':
main.cpp:1261:76: error: cast from 'double*' to 'long int' loses precision [-fpermissive]
 1261 |                 fprintf(logFile, "MALLOC_ERROR map i=%d *energy=%ld\n", i, (long)gridmap[i].energy);
      |                                                                            ^~~~~~~~~~~~~~~~~~~~~~~

```
It works on Ubuntu 24.04 with 
```
# gcc --version
gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

```
but not on mingw64 with
```
# gcc --version
gcc.exe (Rev7, Built by MSYS2 project) 15.1.0
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
